name: firestore_api
description: This project tries to create a plattform independend API in Dart for Cloud Firestore.
version: 0.0.1
homepage: https://www.github.com/dartclub/firestore_dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  dartclub_lint: 0.2.1
  test: ^1.0.0