name: firestore_api
description: This project tries to create a plattform independend API in Dart for Cloud Firestore.
version: 3.0.0
homepage: https://www.github.com/dartclub/firestore_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.16.5