name: firestore_flutter
description: firestore interop for flutter
version: 3.0.0
homepage: https://www.github.com/dartclub/firestore_dart
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cloud_firestore: 4.13.1 # keep until resolved: https://github.com/firebase/flutterfire/issues/12003
  firestore_api:
#    path: ../firestore_api
    git:
      url: https://github.com/dartclub/firestore_dart
      path: firestore_api
  flutter:
    sdk: flutter
  

dev_dependencies:
  test: ^1.16.5