name: firestore_flutter
description: firestore interop for flutter
version: 2.0.0
homepage: https://www.github.com/dartclub/firestore_dart

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.1.13
  firestore_api:
#    path: ../firestore_api
    git:
      url: https://github.com/dartclub/firestore_dart
      path: firestore_api
  flutter:
    sdk: flutter
  

dev_dependencies:
  dartclub_lint: 0.2.1
  test: ^1.16.5